package org.hsq.wjg.demo.codeGenetor.entity;

import java.math.BigDecimal;
import java.util.Date;

/**
* RegularAsset 实体类
*
* Generated by Mybatis-Generator on 2016/10/31 15:34:22
*/
public class RegularAsset {
    private Integer id;
    private String assetSerial;
    private String merchantCode;
    private String productCode;
    private String productName;
    private BigDecimal yearRate;
    private Integer inverstTerm;
    private Long inverstBalance;
    private Date inverstDate;
    private Date startAccrualDate;
    private Date endAccrualDate;
    private Long expectedAccrual;
    private Integer isPayBack;
    private Date createTime;
    private Date updateTime;

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getAssetSerial() {
        return this.assetSerial;
    }

    public void setAssetSerial(String assetSerial) {
        this.assetSerial = assetSerial;
    }

    public String getMerchantCode() {
        return this.merchantCode;
    }

    public void setMerchantCode(String merchantCode) {
        this.merchantCode = merchantCode;
    }

    public String getProductCode() {
        return this.productCode;
    }

    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }

    public String getProductName() {
        return this.productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public BigDecimal getYearRate() {
        return this.yearRate;
    }

    public void setYearRate(BigDecimal yearRate) {
        this.yearRate = yearRate;
    }

    public Integer getInverstTerm() {
        return this.inverstTerm;
    }

    public void setInverstTerm(Integer inverstTerm) {
        this.inverstTerm = inverstTerm;
    }

    public Long getInverstBalance() {
        return this.inverstBalance;
    }

    public void setInverstBalance(Long inverstBalance) {
        this.inverstBalance = inverstBalance;
    }

    public Date getInverstDate() {
        return this.inverstDate;
    }

    public void setInverstDate(Date inverstDate) {
        this.inverstDate = inverstDate;
    }

    public Date getStartAccrualDate() {
        return this.startAccrualDate;
    }

    public void setStartAccrualDate(Date startAccrualDate) {
        this.startAccrualDate = startAccrualDate;
    }

    public Date getEndAccrualDate() {
        return this.endAccrualDate;
    }

    public void setEndAccrualDate(Date endAccrualDate) {
        this.endAccrualDate = endAccrualDate;
    }

    public Long getExpectedAccrual() {
        return this.expectedAccrual;
    }

    public void setExpectedAccrual(Long expectedAccrual) {
        this.expectedAccrual = expectedAccrual;
    }

    public Integer getIsPayBack() {
        return this.isPayBack;
    }

    public void setIsPayBack(Integer isPayBack) {
        this.isPayBack = isPayBack;
    }

    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}
