package org.hsq.wjg.demo.codeGenetor.entity;

import java.math.BigDecimal;
import java.util.Date;

/**
* RegularProduct 实体类
*
* Generated by Mybatis-Generator on 2016/10/31 15:34:22
*/
public class RegularProduct {
    private Integer id;
    private String code;
    private String name;
    private BigDecimal yearRate;
    private Integer inverstTerm;
    private Long amoutStart;
    private Long amoutIncrease;
    private String calAccrualType;
    private String remark;
    private String accountIn;
    private String accountOut;
    private Integer state;
    private Date createTime;
    private Date updateTime;

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public BigDecimal getYearRate() {
        return this.yearRate;
    }

    public void setYearRate(BigDecimal yearRate) {
        this.yearRate = yearRate;
    }

    public Integer getInverstTerm() {
        return this.inverstTerm;
    }

    public void setInverstTerm(Integer inverstTerm) {
        this.inverstTerm = inverstTerm;
    }

    public Long getAmoutStart() {
        return this.amoutStart;
    }

    public void setAmoutStart(Long amoutStart) {
        this.amoutStart = amoutStart;
    }

    public Long getAmoutIncrease() {
        return this.amoutIncrease;
    }

    public void setAmoutIncrease(Long amoutIncrease) {
        this.amoutIncrease = amoutIncrease;
    }

    public String getCalAccrualType() {
        return this.calAccrualType;
    }

    public void setCalAccrualType(String calAccrualType) {
        this.calAccrualType = calAccrualType;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getAccountIn() {
        return this.accountIn;
    }

    public void setAccountIn(String accountIn) {
        this.accountIn = accountIn;
    }

    public String getAccountOut() {
        return this.accountOut;
    }

    public void setAccountOut(String accountOut) {
        this.accountOut = accountOut;
    }

    public Integer getState() {
        return this.state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}
