package org.hsq.wjg.demo.codeGenetor.entity;

import java.util.Date;

/**
* RegularRedeem 实体类
*
* Generated by Mybatis-Generator on 2016/10/31 15:34:22
*/
public class RegularRedeem {
    private Integer id;
    private String orderNo;
    private Integer assetId;
    private Long balance;
    private Long accrual;
    private Integer state;
    private Date createTime;
    private Date updateTime;

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getOrderNo() {
        return this.orderNo;
    }

    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    public Integer getAssetId() {
        return this.assetId;
    }

    public void setAssetId(Integer assetId) {
        this.assetId = assetId;
    }

    public Long getBalance() {
        return this.balance;
    }

    public void setBalance(Long balance) {
        this.balance = balance;
    }

    public Long getAccrual() {
        return this.accrual;
    }

    public void setAccrual(Long accrual) {
        this.accrual = accrual;
    }

    public Integer getState() {
        return this.state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}
