package org.hsq.wjg.demo.codeGenetor.service.impl;

import org.hsq.wjg.demo.codeGenetor.dao.IRegularAssetDao;
import org.hsq.wjg.demo.codeGenetor.entity.RegularAsset;
import org.hsq.wjg.demo.codeGenetor.service.IRegularAssetService;
import org.springframework.beans.factory.annotation.Autowired;
import java.util.Date;

/**
  * RegularAsset 操作service
  *
  * Generated by Mybatis-Generator on 2016/10/31 15:34:22
  */
public class RegularAssetServiceImpl implements IRegularAssetService {
	@Autowired
	private IRegularAssetDao regularAssetDao;

	/**
	  * 根据id查询 RegularAsset
	  * @param id
	  */
	public RegularAsset queryById(Integer id) {
		return regularAssetDao.queryById(id);
	}

	/**
	  * 新增 RegularAsset
	  */
	public void add(RegularAsset regularAsset) {
		regularAsset.setCreateTime(new Date());
		regularAssetDao.add(regularAsset);
	}

	/**
	  * 更新 RegularAsset
	  */
	public void update(RegularAsset regularAsset) {
		regularAsset.setUpdateTime(new Date());
		regularAssetDao.update(regularAsset);
	}
}