package org.hsq.wjg.demo.codeGenetor.service.impl;

import org.hsq.wjg.demo.codeGenetor.dao.IRegularPurchaseDao;
import org.hsq.wjg.demo.codeGenetor.entity.RegularPurchase;
import org.hsq.wjg.demo.codeGenetor.service.IRegularPurchaseService;
import org.springframework.beans.factory.annotation.Autowired;
import java.util.Date;

/**
  * RegularPurchase 操作service
  *
  * Generated by Mybatis-Generator on 2016/10/31 15:34:22
  */
public class RegularPurchaseServiceImpl implements IRegularPurchaseService {
	@Autowired
	private IRegularPurchaseDao regularPurchaseDao;

	/**
	  * 根据id查询 RegularPurchase
	  * @param id
	  */
	public RegularPurchase queryById(Integer id) {
		return regularPurchaseDao.queryById(id);
	}

	/**
	  * 新增 RegularPurchase
	  */
	public void add(RegularPurchase regularPurchase) {
		regularPurchase.setCreateTime(new Date());
		regularPurchaseDao.add(regularPurchase);
	}

	/**
	  * 更新 RegularPurchase
	  */
	public void update(RegularPurchase regularPurchase) {
		regularPurchase.setUpdateTime(new Date());
		regularPurchaseDao.update(regularPurchase);
	}
}