package org.hsq.wjg.demo.codeGenetor.service.impl;

import org.hsq.wjg.demo.codeGenetor.dao.IRegularHolidayDao;
import org.hsq.wjg.demo.codeGenetor.entity.RegularHoliday;
import org.hsq.wjg.demo.codeGenetor.service.IRegularHolidayService;
import org.springframework.beans.factory.annotation.Autowired;
import java.util.Date;

/**
  * RegularHoliday 操作service
  *
  * Generated by Mybatis-Generator on 2016/10/31 15:34:22
  */
public class RegularHolidayServiceImpl implements IRegularHolidayService {
	@Autowired
	private IRegularHolidayDao regularHolidayDao;

	/**
	  * 根据id查询 RegularHoliday
	  * @param id
	  */
	public RegularHoliday queryById(Integer id) {
		return regularHolidayDao.queryById(id);
	}

	/**
	  * 新增 RegularHoliday
	  */
	public void add(RegularHoliday regularHoliday) {
		regularHoliday.setCreateTime(new Date());
		regularHolidayDao.add(regularHoliday);
	}

	/**
	  * 更新 RegularHoliday
	  */
	public void update(RegularHoliday regularHoliday) {
		regularHoliday.setUpdateTime(new Date());
		regularHolidayDao.update(regularHoliday);
	}
}