CREATE DATABASE IF NOT EXISTS `MANDAO_PROD_FB` DEFAULT CHARACTER SET utf8;

USE `MANDAO_PROD_FB`;

/*Table structure for table `FB_PURCHASE` */
DROP TABLE IF EXISTS `FB_PURCHASE`;
CREATE TABLE `FB_PURCHASE` (
    `ID` int(11) NOT NULL AUTO_INCREMENT,
    `BILL_NO` varchar(64) NOT NULL  COMMENT '单号',
    `USER_ID` varchar(64) NOT NULL  COMMENT '理财用户ID',
    `USER_NAME` varchar(64) NULL DEFAULT NULL COMMENT '理财用户名称',
    `PROD_CODE` varchar(64) NULL DEFAULT NULL COMMENT '产品编号',
    `PROD_NAME` varchar(64) NULL DEFAULT NULL COMMENT '资产名称',
    `ASSET_CODE` varchar(64) NULL DEFAULT NULL COMMENT '资产编号',
    `BUY_AMOUNT` decimal(18,4) NOT NULL  COMMENT '金额(以元为单位,2位精度)',
    `BUT_TIME` date NOT NULL  COMMENT '购买时间',
    `STATE` int(2) NULL DEFAULT NULL COMMENT '状态(0:初始化,1:成功,-1:失败)',
    `ASSET_BILL_NO` varchar(64) NULL DEFAULT NULL COMMENT '资产申购单号',
    `CREATE_TIME` timestamp DEFAULT NULL COMMENT '创建时间',
    `UPDATE_TIME` timestamp DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `FB_REDEEM` */
DROP TABLE IF EXISTS `FB_REDEEM`;
CREATE TABLE `FB_REDEEM` (
    `ID` int(11) NOT NULL AUTO_INCREMENT,
    `BILL_NO` varchar(64) NOT NULL  COMMENT '单号',
    `USER_ID` varchar(64) NOT NULL  COMMENT '理财用户ID',
    `USER_NAME` varchar(64) NULL DEFAULT NULL COMMENT '理财用户名称',
    `PROD_CODE` varchar(64) NOT NULL  COMMENT '产品编号',
    `PROD_NAME` varchar(64) NULL DEFAULT NULL COMMENT '产品名称',
    `ASSET_CODE` varchar(64) NULL DEFAULT NULL COMMENT '资产编号',
    `CAPITAL_SERIAL` varchar(64) NOT NULL  COMMENT '用户资产序列号',
    `REDEEM_AMOUNT` decimal(18,4) NOT NULL  COMMENT '金额(以元为单位,2位精度)',
    `IS_ENTIRE` int(2) NOT NULL  COMMENT '是否全部赎回 (1:是 0:否)',
    `REDEEM_TYPE` varchar(8) NOT NULL  COMMENT '赎回方式(T+N)',
    `REDEEM_TIME` date NOT NULL  COMMENT '赎回时间(精确到秒)',
    `STATE` int(2) NULL DEFAULT NULL COMMENT '状态(0:初始化,1:成功,-1:失败)',
    `ASSET_BILL_NO` varchar(64) NULL DEFAULT NULL COMMENT '资产赎回单号',
    `REMARK` varchar(64) NULL DEFAULT NULL COMMENT '备注',
    `CREATE_TIME` timestamp DEFAULT NULL COMMENT '创建时间',
    `UPDATE_TIME` timestamp DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

