CREATE DATABASE IF NOT EXISTS `MANDAO_PROD_FB` DEFAULT CHARACTER SET utf8;

USE `MANDAO_PROD_FB`;

/*Table structure for table `FB_PURCHASE` */
DROP TABLE IF EXISTS `FB_PURCHASE`;
CREATE TABLE `FB_PURCHASE` (
    `ID` int(11) NOT NULL AUTO_INCREMENT,
    `BILL_NO` varchar(64) NOT NULL  COMMENT '单号',
    `USER_ID` varchar(64) NOT NULL  COMMENT '用户ID',
    `USER_NAME` varchar(64) NULL DEFAULT NULL COMMENT '用户名称',
    `ASSET_CODE` varchar(64) NULL DEFAULT NULL COMMENT '资产编号',
    `ASSET_NAME` varchar(64) NULL DEFAULT NULL COMMENT '资产名称',
    `BUY_AMOUNT` decimal(18,4) NULL DEFAULT NULL COMMENT '金额,以元为单位,2位精度',
    `BUT_TIME` datetime NULL DEFAULT NULL COMMENT '购买时间,精确到秒',
    `STATE` int(2) NULL DEFAULT NULL COMMENT '状态,0:初始化,1:成功,-1:失败',
    `ASSET_BILL_NO` varchar(64) NULL DEFAULT NULL COMMENT '资产申购单号',
    `CREATE_TIME` timestamp DEFAULT NULL COMMENT '创建时间',
    `UPDATE_TIME` timestamp DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `FB_REDEEM` */
DROP TABLE IF EXISTS `FB_REDEEM`;
CREATE TABLE `FB_REDEEM` (
    `ID` int(11) NOT NULL AUTO_INCREMENT,
    `BILL_NO` varchar(64) NOT NULL  COMMENT '单号',
    `USER_ID` varchar(64) NOT NULL  COMMENT '用户ID',
    `USER_NAME` varchar(64) NULL DEFAULT NULL COMMENT '用户名称',
    `ASSET_CODE` varchar(64) NULL DEFAULT NULL COMMENT '资产Code',
    `ASSET_NAME` varchar(64) NULL DEFAULT NULL COMMENT '资产名称',
    `CAPITALSERIAL` varchar(64) NULL DEFAULT NULL COMMENT '用户资产序列号,用户资产序列号(定期)',
    `REDEEMAMOUNT` decimal(18,4) NULL DEFAULT NULL COMMENT '金额,以元为单位,2位精度',
    `ISENTIRE` tinyint(2) NULL DEFAULT NULL COMMENT '是否全部赎回 (0:是 1:否)',
    `REDEEMTYPE` varchar(8) NULL DEFAULT NULL COMMENT '赎回方式,T+N',
    `REDEEMTIME` datetime NULL DEFAULT NULL COMMENT '赎回时间,精确到秒',
    `STATE` tinyint(2) NULL DEFAULT NULL COMMENT '状态,0:初始化,1:成功,-1:失败',
    `ASSET_BILL_NO` varchar(64) NULL DEFAULT NULL COMMENT '资产赎回单号',
    `REMARK` varchar(64) NULL DEFAULT NULL COMMENT '备注',
    `OPERATOR_ID` varchar(32) NULL DEFAULT NULL COMMENT '操作人',
    `CREATE_TIME` timestamp DEFAULT NULL COMMENT '创建时间',
    `UPDATE_TIME` timestamp DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

