package org.hsq.wjg.demo.codeGenetor.dao;

import org.hsq.wjg.demo.codeGenetor.entity.RegularHoliday;
import java.util.List;
import org.apache.ibatis.annotations.Param;

/**
  * RegularHoliday 数据库操作
  *
  * Generated by Mybatis-Generator on 2016/10/31 15:34:22
  */
public interface IRegularHolidayDao {
    List<RegularHoliday> query(RegularHoliday $entityNameVar);

    RegularHoliday queryById(@Param("id") Integer id);

    void add(RegularHoliday $entityNameVar);

    void update(RegularHoliday $entityNameVar);
}