package org.hsq.wjg.demo.codeGenetor.dao;

import org.hsq.wjg.demo.codeGenetor.entity.RegularRedeem;
import java.util.List;
import org.apache.ibatis.annotations.Param;

/**
  * RegularRedeem 数据库操作
  *
  * Generated by Mybatis-Generator on 2016/10/31 15:34:22
  */
public interface IRegularRedeemDao {
    List<RegularRedeem> query(RegularRedeem $entityNameVar);

    RegularRedeem queryById(@Param("id") Integer id);

    void add(RegularRedeem $entityNameVar);

    void update(RegularRedeem $entityNameVar);
}