package org.hsq.wjg.demo.codeGenetor.service;

import org.hsq.wjg.demo.codeGenetor.entity.RegularTransferTrade;

/**
  * RegularTransferTrade 操作service
  *
  * Generated by Mybatis-Generator on 2016/10/31 15:34:22
  */
public interface IRegularTransferTradeService {
	/**
	  * 根据id查询 RegularTransferTrade
	  * @param id
	  */
	RegularTransferTrade queryById(Integer id);

	/**
	  * 新增 RegularTransferTrade
	  */
	void add(RegularTransferTrade regularTransferTrade);

	/**
	  * 更新 RegularTransferTrade
	  */
	void update(RegularTransferTrade regularTransferTrade);
}