package org.hsq.wjg.demo.codeGenetor.service;

import org.hsq.wjg.demo.codeGenetor.entity.RegularHoliday;

/**
  * RegularHoliday 操作service
  *
  * Generated by Mybatis-Generator on 2016/10/31 15:34:22
  */
public interface IRegularHolidayService {
	/**
	  * 根据id查询 RegularHoliday
	  * @param id
	  */
	RegularHoliday queryById(Integer id);

	/**
	  * 新增 RegularHoliday
	  */
	void add(RegularHoliday regularHoliday);

	/**
	  * 更新 RegularHoliday
	  */
	void update(RegularHoliday regularHoliday);
}