package org.hsq.wjg.demo.codeGenetor.service;

import org.hsq.wjg.demo.codeGenetor.entity.RegularPurchase;

/**
  * RegularPurchase 操作service
  *
  * Generated by Mybatis-Generator on 2016/10/31 15:34:22
  */
public interface IRegularPurchaseService {
	/**
	  * 根据id查询 RegularPurchase
	  * @param id
	  */
	RegularPurchase queryById(Integer id);

	/**
	  * 新增 RegularPurchase
	  */
	void add(RegularPurchase regularPurchase);

	/**
	  * 更新 RegularPurchase
	  */
	void update(RegularPurchase regularPurchase);
}