package org.hsq.wjg.demo.codeGenetor.service;

import org.hsq.wjg.demo.codeGenetor.entity.RegularProduct;

/**
  * RegularProduct 操作service
  *
  * Generated by Mybatis-Generator on 2016/10/31 15:34:22
  */
public interface IRegularProductService {
	/**
	  * 根据id查询 RegularProduct
	  * @param id
	  */
	RegularProduct queryById(Integer id);

	/**
	  * 新增 RegularProduct
	  */
	void add(RegularProduct regularProduct);

	/**
	  * 更新 RegularProduct
	  */
	void update(RegularProduct regularProduct);
}